export const projects = [
  {
    id: 1,
    title: "Modern Office Complex",
    category: "Commercial",
    beforeImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
    description: "Complete renovation of a 50,000 sq ft office building with modern amenities and sustainable design.",
    location: "Downtown Business District",
    duration: "18 months",
    budget: "$12M",
    features: ["LEED Certified", "Smart Building Systems", "Green Roof", "Solar Panels"],
  },
  {
    id: 2,
    title: "Luxury Residential Estate",
    category: "Residential",
    beforeImage: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
    description: "Custom-built 8,000 sq ft luxury home with premium finishes and smart home integration.",
    location: "Exclusive Suburban Community",
    duration: "14 months",
    budget: "$4.5M",
    features: ["Custom Architecture", "Premium Materials", "Smart Home Tech", "Landscaping"],
  },
  {
    id: 3,
    title: "Industrial Warehouse Facility",
    category: "Industrial",
    beforeImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    description: "New construction of a 200,000 sq ft distribution center with advanced logistics systems.",
    location: "Industrial Park",
    duration: "24 months",
    budget: "$25M",
    features: ["Automated Systems", "Energy Efficient", "Loading Docks", "Office Space"],
  },
  {
    id: 4,
    title: "Historic Building Restoration",
    category: "Restoration",
    beforeImage: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?w=800&h=600&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?w=800&h=600&fit=crop",
    description: "Careful restoration of a 1920s landmark building preserving original architectural details.",
    location: "Historic District",
    duration: "20 months",
    budget: "$8M",
    features: ["Historic Preservation", "Modern Upgrades", "ADA Compliance", "Energy Retrofit"],
  },
  {
    id: 5,
    title: "Mixed-Use Development",
    category: "Commercial",
    beforeImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop",
    description: "Multi-phase development combining retail, residential, and office spaces in urban core.",
    location: "City Center",
    duration: "36 months",
    budget: "$45M",
    features: ["Mixed Use", "Parking Garage", "Public Spaces", "Transit Access"],
  },
  {
    id: 6,
    title: "Healthcare Facility",
    category: "Healthcare",
    beforeImage: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800&h=600&fit=crop",
    afterImage: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop",
    description: "State-of-the-art medical center with advanced facilities and patient care areas.",
    location: "Medical District",
    duration: "30 months",
    budget: "$35M",
    features: ["Medical Grade", "Advanced HVAC", "Emergency Systems", "Accessibility"],
  },
]

export const services = [
  {
    id: 1,
    title: "Commercial Construction",
    icon: "Building",
    description: "Full-service commercial construction from design to completion. Offices, retail, and mixed-use developments.",
    features: ["Project Management", "Design-Build", "Tenant Improvements", "Renovations"],
  },
  {
    id: 2,
    title: "Residential Construction",
    icon: "Home",
    description: "Custom homes and residential developments built to the highest standards of quality and craftsmanship.",
    features: ["Custom Homes", "Additions", "Renovations", "Multi-Family"],
  },
  {
    id: 3,
    title: "Industrial Construction",
    icon: "Factory",
    description: "Heavy-duty industrial facilities, warehouses, and manufacturing plants with specialized requirements.",
    features: ["Warehouses", "Manufacturing", "Distribution Centers", "Specialized Systems"],
  },
  {
    id: 4,
    title: "Renovation & Remodeling",
    icon: "Hammer",
    description: "Transform existing spaces with expert renovation services that preserve character while adding modern functionality.",
    features: ["Interior Renovation", "Exterior Upgrades", "Historic Restoration", "Modernization"],
  },
  {
    id: 5,
    title: "Project Management",
    icon: "Clipboard",
    description: "Comprehensive project management ensuring on-time, on-budget delivery with transparent communication.",
    features: ["Scheduling", "Budget Management", "Quality Control", "Stakeholder Communication"],
  },
  {
    id: 6,
    title: "Design-Build Services",
    icon: "PenTool",
    description: "Integrated design and construction services for seamless project delivery from concept to completion.",
    features: ["Architectural Design", "Engineering", "Construction", "Single Point Contact"],
  },
]

export const certifications = [
  {
    id: 1,
    name: "LEED Certified",
    description: "Leadership in Energy and Environmental Design",
    icon: "Leaf",
  },
  {
    id: 2,
    name: "OSHA Certified",
    description: "Occupational Safety and Health Administration",
    icon: "Shield",
  },
  {
    id: 3,
    name: "Licensed & Bonded",
    description: "Fully licensed and bonded contractors",
    icon: "BadgeCheck",
  },
  {
    id: 4,
    name: "BBB A+ Rating",
    description: "Better Business Bureau Accredited",
    icon: "Star",
  },
  {
    id: 5,
    name: "ISO 9001",
    description: "Quality Management Systems Certified",
    icon: "Award",
  },
  {
    id: 6,
    name: "Green Building",
    description: "Sustainable construction practices",
    icon: "Recycle",
  },
]

export const guarantees = [
  {
    id: 1,
    title: "Quality Guarantee",
    description: "100% satisfaction guarantee on all workmanship. We stand behind every project we complete.",
    icon: "CheckCircle",
  },
  {
    id: 2,
    title: "On-Time Delivery",
    description: "We commit to completing your project on schedule. Delays are rare, and we communicate proactively.",
    icon: "Clock",
  },
  {
    id: 3,
    title: "Budget Transparency",
    description: "No hidden costs or surprise charges. Clear, upfront pricing with detailed estimates.",
    icon: "DollarSign",
  },
  {
    id: 4,
    title: "Warranty Protection",
    description: "Comprehensive warranty coverage on materials and workmanship for your peace of mind.",
    icon: "Shield",
  },
]

